added menu page
Mr-Rovilay/book-a-meal pull request #4
Opened 2024-03-09 21:12 UTC by Mr-Rovilay

https://signin-signup-3.onrender.com

2024-03-10 19:04 UTC, rovilay requested changes

2024-03-10 19:04 UTC, rovilay commented on client/src/components/Offer.jsx
> +            our table
Put this text in a dark transparent background or remove it.

2024-03-10 19:04 UTC, rovilay commented on client/src/pages/MenuPage.jsx
> +                    <p className="text-dark-grey text-2xl mt-3">{item.desc}</p>
your menu page isn't properly designed.

![Uploading Screenshot 2024-03-10 at 19.59.52.png…]()

2024-03-10 19:04 UTC, rovilay commented on client/src/pages/MenuPage.jsx
> +                    </button>
Your buttons should have the same styles all through the app. Compare `add to cart` and `signup`  buttons.

2024-03-14 02:59 UTC, Mr-Rovilay commented on client/src/pages/MenuPage.jsx
> +                    <p className="text-dark-grey text-2xl mt-3">{item.desc}</p>
check the review bro.. im done with this

2024-03-17 15:40 UTC, merged